MODEL:
  BASE_1_CHANNELS: 256
  BASE_2_CHANNELS: 64
  FLOW_CHANNELS: 2
  IN_CHANNELS: 3
  OUT_CHANNELS: 3
  SRNET_A:
    STAGE: 3
  SRNET_B:
    STAGE: 5
  SRNET_C:
    STAGE: 5
  SRNET_D:
    STAGE: 5
SCALE_FACTOR: 2
SEQUENCE_SIZE: 7
TEST:
  BATCH_SIZE: 1

